// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: rsyncovergrpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rsync_Rsync_FullMethodName = "/rsyncovergrpc.Rsync/Rsync"
)

// RsyncClient is the client API for Rsync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RsyncClient interface {
	Rsync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransferChunk, TransferChunk], error)
}

type rsyncClient struct {
	cc grpc.ClientConnInterface
}

func NewRsyncClient(cc grpc.ClientConnInterface) RsyncClient {
	return &rsyncClient{cc}
}

func (c *rsyncClient) Rsync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransferChunk, TransferChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rsync_ServiceDesc.Streams[0], Rsync_Rsync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferChunk, TransferChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rsync_RsyncClient = grpc.BidiStreamingClient[TransferChunk, TransferChunk]

// RsyncServer is the server API for Rsync service.
// All implementations must embed UnimplementedRsyncServer
// for forward compatibility.
type RsyncServer interface {
	Rsync(grpc.BidiStreamingServer[TransferChunk, TransferChunk]) error
	mustEmbedUnimplementedRsyncServer()
}

// UnimplementedRsyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRsyncServer struct{}

func (UnimplementedRsyncServer) Rsync(grpc.BidiStreamingServer[TransferChunk, TransferChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Rsync not implemented")
}
func (UnimplementedRsyncServer) mustEmbedUnimplementedRsyncServer() {}
func (UnimplementedRsyncServer) testEmbeddedByValue()               {}

// UnsafeRsyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RsyncServer will
// result in compilation errors.
type UnsafeRsyncServer interface {
	mustEmbedUnimplementedRsyncServer()
}

func RegisterRsyncServer(s grpc.ServiceRegistrar, srv RsyncServer) {
	// If the following call pancis, it indicates UnimplementedRsyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rsync_ServiceDesc, srv)
}

func _Rsync_Rsync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RsyncServer).Rsync(&grpc.GenericServerStream[TransferChunk, TransferChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rsync_RsyncServer = grpc.BidiStreamingServer[TransferChunk, TransferChunk]

// Rsync_ServiceDesc is the grpc.ServiceDesc for Rsync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rsync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsyncovergrpc.Rsync",
	HandlerType: (*RsyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Rsync",
			Handler:       _Rsync_Rsync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rsyncovergrpc.proto",
}
